before_script:
  - if ! gem list "fastlane" -i > /dev/null 2>&1; then echo "fastlane not installed. Installing..."; gem install fastlane; fi 
  - if ! gem list "cocoapods" -i > /dev/null 2>&1; then echo "cocoapods not installed. Installing..."; gem install cocoapods; fi   
  - cd OhMyBox
stages:
  - deploy
deploy_beta:
  stage: deploy
  script:
    - fastlane beta
  only:
    - dev
deploy_production:
  stage: deploy
  script:
    - fastlane release
  only:
    - master