lane :beta do
  increment_build_number
  match(type: "appstore")       # see code signing guide for more information
  clear_derived_data
  cocoapods
  gym(scheme: "OhMyBox",  use_legacy_build_api: true)
  changelog_from_git_commits
  testflight
end
lane :release do
  increment_version_number
  # snapshot                      # generate new screenshots for the App Store
  match(type: "appstore")       # see code signing guide for more information
  gym(scheme: "OhMyBox",  use_legacy_build_api: true)          # build your app
  appstore                      # upload your app to iTunes Connect
  # slack(message: "Successfully uploaded a new App Store build")
end
