# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

def common_pods
    # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
    inhibit_all_warnings!
    use_frameworks!

    pod 'Parse'
    pod 'ParseFacebookUtilsV4'
    pod 'Fabric'
    pod 'Crashlytics'
    pod 'BGTableViewRowActionWithImage'
    pod 'FalconFrameworkIOSSDK', :git => 'https://gitlab.com/LAB262/FalconFrameworkIOSSDK.git'


end

target 'lab262.ohmybox.store.dev' do
    common_pods
end

target 'lab262.ohmybox.store.test' do
    common_pods
end

target 'lab262.ohmybox.store.production' do
    common_pods
end

target 'OhMyBoxTests' do
    inherit! :search_paths
    common_pods
    # Pods for testing
end
