# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'OhMyBox' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

    pod 'Parse'
    pod 'Fabric'
    pod 'Crashlytics'
    pod 'BGTableViewRowActionWithImage'
    pod 'FalconFrameworkIOSSDK', :git => 'https://gitlab.com/LAB262/FalconFrameworkIOSSDK.git'

# Pods for OhMyBox

  target 'OhMyBoxTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
